apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-permissions
rules:
- apiGroups: [""]
  resources: ["*"]  
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-permissions-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: metrics-go-app-namespace 
roleRef:
  kind: ClusterRole
  name: all-permissions
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-list-reader
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list", "get", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-list-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: metrics-go-app-namespace
roleRef:
  kind: ClusterRole
  name: deployment-list-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-go-app-default-deployment-list-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: metrics-go-app-namespace
roleRef:
  kind: ClusterRole
  name: deployment-list-reader
  apiGroup: rbac.authorization.k8s.io
