
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-go-app-namespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-go-app
  namespace: metrics-go-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-go-app-service
  template:
    metadata:
      labels:
        app: metrics-go-app-service
    spec:
      containers:
      - name: metrics-go-app-service
        image: raushan2231/metrics_service:v24
        imagePullPolicy: Always
        ports:
        - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: metrics-go-app-service
  namespace: metrics-go-app-namespace
  labels:
    app: metrics-go-app-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8082
  selector:
    app: metrics-go-app-service

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-go-app-service-monitor
  namespace: metrics-go-app-namespace
  labels:
    app: metrics-go-app-service
spec:
  selector:
    matchLabels:
      app: metrics-go-app-service
  endpoints:
  - port: http
    interval: 5s
    path: /metrics
  targetLabels:
    - app
  jobLabel: app
